
--sdev350mrieser_audit.sql

DROP TABLESPACE table_audit INCLUDING CONTENTS;
CREATE TABLESPACE table_audit
DATAFILE SIZE 50M;

--TEMPORARY TABLESPACE CREATED
DROP TABLESPACE TEMP_usersTable INCLUDING CONTENTS;
CREATE TEMPORARY TABLESPACE TEMP_usersTable
TEMPFILE SIZE 50M;

--CREATE PROFILE
DROP PROFILE user_profile CASCADE;
CREATE PROFILE user_profile 
LIMIT
    PASSWORD_REUSE_MAX         3
    PASSWORD_REUSE_TIME        30
    SESSIONS_PER_USER          2 
    CPU_PER_SESSION            UNLIMITED 
    CPU_PER_CALL               3000 
    CONNECT_TIME               45 
    LOGICAL_READS_PER_SESSION  DEFAULT 
    LOGICAL_READS_PER_CALL     1000 
    PRIVATE_SGA                15K
    COMPOSITE_LIMIT            500000
    FAILED_LOGIN_ATTEMPTS      3
    PASSWORD_LIFE_TIME 30
    PASSWORD_LOCK_TIME 7
    PASSWORD_GRACE_TIME 10
    PASSWORD_VERIFY_FUNCTION ora12c_verify_function;
    
-- USER CREATION DBA1 
DROP USER DBA1 CASCADE;
CREATE USER DBA1 IDENTIFIED BY "Pa$$w0rd"  
--PASSWORD EXPIRE
DEFAULT TABLESPACE "TABLE_AUDIT"
TEMPORARY TABLESPACE "TEMP_USERSTABLE"
PROFILE user_profile;

-- ROLES 
GRANT CONNECT, "DBA" TO DBA1;
GRANT CREATE SESSION TO DBA1;

--ENABLE UNIFIED AUDITING
EXECUTE  DBMS_AUDIT_MGMT.SET_AUDIT_TRAIL_PROPERTY(DBMS_AUDIT_MGMT.AUDIT_TRAIL_UNIFIED, DBMS_AUDIT_MGMT.AUDIT_TRAIL_WRITE_MODE, DBMS_AUDIT_MGMT.AUDIT_TRAIL_IMMEDIATE_WRITE);

--AUDIT SESSION FOR DBA1
AUDIT SESSION
BY DBA1;

SELECT * FROM dba_segments WHERE TABLESPACE_NAME='TABLE_AUDIT' ORDER BY bytes DESC;

SELECT USERNAME,PROFILE, ACCOUNT_STATUS FROM DBA_USERS ORDER BY PROFILE DESC;

select parameter,value from v$option where parameter='Unified Auditing';

select * from DBA_AUDIT_SESSION;
