--Creating TABLESPACES TABLE_USERS AND TABLE_APPLICATIONS
DROP TABLESPACE Table_users INCLUDING CONTENTS;
DROP TABLESPACE Table_applications INCLUDING CONTENTS;
CREATE TABLESPACE Table_users
DATAFILE SIZE 50M;
CREATE TABLESPACE Table_applications
DATAFILE SIZE 50M;

--TEMPORARY TABLESPACE CREATED
DROP TABLESPACE TEMP_usersTable;
DROP TABLESPACE TEMP_appsTable;
CREATE TEMPORARY TABLESPACE TEMP_usersTable
TEMPFILE SIZE 50M;
CREATE TEMPORARY TABLESPACE TEMP_appsTable
TEMPFILE SIZE 50M;

--CREATE PROFILE
DROP PROFILE user_profile CASCADE;
CREATE PROFILE user_profile 
LIMIT
    PASSWORD_REUSE_MAX         3
    PASSWORD_REUSE_TIME        30
    SESSIONS_PER_USER          2 
    CPU_PER_SESSION            UNLIMITED 
    CPU_PER_CALL               3000 
    CONNECT_TIME               45 
    LOGICAL_READS_PER_SESSION  DEFAULT 
    LOGICAL_READS_PER_CALL     1000 
    PRIVATE_SGA                15K
    COMPOSITE_LIMIT            500000
    FAILED_LOGIN_ATTEMPTS      3
    PASSWORD_LIFE_TIME 30
    PASSWORD_LOCK_TIME 7
    PASSWORD_GRACE_TIME 10
    PASSWORD_VERIFY_FUNCTION ora12c_verify_function;
    
-- USER CREATION DBA1 and DBA2
DROP USER DBA1;
CREATE USER DBA1 IDENTIFIED BY "Pa$$w0rd"  
--PASSWORD EXPIRE
DEFAULT TABLESPACE "TABLE_USERS"
TEMPORARY TABLESPACE "TEMP_USERSTABLE"
PROFILE user_profile;

DROP USER DBA2;
CREATE USER DBA2 IDENTIFIED BY "Pa$$w0rd"   
--PASSWORD EXPIRE
DEFAULT TABLESPACE "TABLE_APPLICATIONS"
TEMPORARY TABLESPACE "TEMP_APPSTABLE"
PROFILE user_profile;

-- QUOTAS
ALTER USER DBA1 QUOTA 500K ON Table_users;
ALTER USER DBA2 QUOTA 500K ON Table_users;
ALTER USER DBA1 QUOTA 500K ON Table_APPLICATIONS;
ALTER USER DBA2 QUOTA 500K ON Table_APPLICATIONS;

-- ROLES 
GRANT CONNECT, "DBA" TO DBA1;
GRANT CONNECT, "DBA" TO DBA2;
GRANT CREATE SESSION TO DBA1;
GRANT CREATE SESSION TO DBA2;



--SELECT * FROM dba_segments WHERE TABLESPACE_NAME='TABLE_USERS' ORDER BY bytes DESC;
--SELECT * FROM dba_segments WHERE TABLESPACE_NAME='TABLE_APPLICATIONS' ORDER BY bytes DESC;

--SELECT * FROM DBA_ROLE_PRIVS ORDER BY GRANTEE ASC;


